from . import purchase_order
from . import purchase_order_line
from . import purchase_invoice_tag
from . import res_partner
from . import product_selector
from . import account_budget_line
from . import hr_department
from . import product_template
from . import product_category
from . import budget_validation_wizard
from . import ir_attachment
from . import account_move