#from . import pos_loyalty_reference
from . import pos_config
from . import pos_session
from . import hr_employee
from . import pos_order
from . import pos_order_line
from . import res_config_settings
from . import pos_payment_method
from . import loyalty_card
from . import res_partner
from . import product_template